[build]
  publish = "frontend/dist"
  command = "npm install -g npm@10 && cd frontend && npm install --legacy-peer-deps && npm run build"

[build.environment]
  NODE_VERSION = "20.0.0"
  NPM_VERSION = "10"
  CI = "false"
  NPM_FLAGS = "--legacy-peer-deps --force"

[context.production.environment]
  NODE_VERSION = "20.0.0"
  NPM_VERSION = "10"

[dev]
  command = "cd frontend && npm run dev"
  port = 5173

# SPA routing for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
