[build]
  base = "./frontend"
  command = "cd frontend && npm install && npm run build"
  publish = "./frontend/dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  CI = "false"

# SPA routing for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
