[build]
  base = "."
  command = "n 20.0.0 && cd frontend && npm install --legacy-peer-deps && npm run build"
  publish = "frontend/dist"
  
[dev]
  command = "cd frontend && npm run dev"
  port = 5173  # Default Vite port

[build.environment]
  NODE_VERSION = "20.0.0"
  NPM_VERSION = "10"
  CI = "false"
  NPM_FLAGS = "--legacy-peer-deps"
  NPM_FLAGS = "--force"

[context.production.environment]
  NODE_VERSION = "20.0.0"
  NPM_VERSION = "10"

# SPA routing for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
