# Netlify build configuration for Vite (React)

[build]
   base = "."
  command = "cd frontend && npm ci && npm run build"
  publish = "frontend/dist"

[build.environment]
  NODE_VERSION = "20"

# SPA routing for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
