# Netlify build configuration for Vite (React)

[build]
  base = "frontend"
  command = "npm ci && npm run build"
  publish = "frontend/dist"

[build.environment]
  NODE_VERSION = "20"

# SPA routing so React Router works on hard refresh
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
